### ISSUE TITLE
mobile_netv2/Bottleneck_B5_3/Bottleneck_B5_3_conv/depthwise_kernel has 'None' for gradient

### ISSUE THREAD

**Issue by Markets00** [saunack/MobileNetv2-SSD#1]
Hi @saunack! I'm trying to reproduce your code locally in my machine.
SO: Ubuntu 20.04.3
Python: 3.8.2
TensorFlow: 2.6.0
Keras: 2.6.0

I've just copied your code in a .py file (I'm copying it at the end of the issue)
First, I had this error when executing **_model.model().summary()_**:
> The graph tensor has name: mobile_netv2/Bottleneck_B5_3/Bottleneck_B5_3_expand_ReLU/Relu6:0

Which I solved adding this line:
`tf.compat.v1.disable_eager_execution()`
as suggested here: https://stackoverflow.com/questions/60551145/tensorflow-2-1-0-an-op-outside-of-the-function-building-code-is-being-passed-a

Then, I'm stuck with this error when executing _**model.fit(...**_:
> Traceback (most recent call last):
  File "ssd_mobilenet_train.py", line 493, in <module>
    history = model.fit(train_dataset,
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/engine/training_v1.py", line 777, in fit
    return func.fit(
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 640, in fit
    return fit_loop(
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 177, in model_iteration
    f = _make_execution_function(model, mode)
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/engine/training_arrays_v1.py", line 547, in _make_execution_function
    return model._make_execution_function(mode)
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/engine/training_v1.py", line 2079, in _make_execution_function
    self._make_train_function()
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/engine/training_v1.py", line 2010, in _make_train_function
    updates = self.optimizer.get_updates(
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 759, in get_updates
    grads = self.get_gradients(loss, params)
  File "/home/aisoy/.local/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 751, in get_gradients
    raise ValueError("Variable {} has `None` for gradient. "
ValueError: Variable <tf.Variable 'mobile_netv2/Bottleneck_B5_3/Bottleneck_B5_3_conv/depthwise_kernel:0' shape=(3, 3, 576, 1) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

Here, they suggest that there are unused weights and gradient can't be computed:
https://github.com/keras-team/keras/issues/12521

My code:
[ssd_mobilenet_train.txt](https://github.com/saunack/MobileNetv2-SSD/files/7210345/ssd_mobilenet_train.txt)

**Comment by Markets00** [comment]
My code
[ssd_mobilenet_train.txt](https://github.com/saunack/MobileNetv2-SSD/files/7210343/ssd_mobilenet_train.txt)

**Comment by saunack** [comment]
Hi @Markets00 . Thanks for pointing it out. This is thrown due to the way Keras model summary works. As for the gradient issue, to be frank, I have a few ideas but I am not sure about the exact one for this case. 
For a workaround, you can keep the eager execution enabled and comment out the model summary. In this case, the training will proceed with a warning (which you can ignore)

**Comment by saunack** [comment]
Related to #3 . Fixed in latest code on master
